# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d84f36bc728685f003512673041ff4d6a32383a7c72dc8f14d269b1fa307a2a4db499b3167c13b92fcad35bdc488e088839e707d7c8360ea38d10e9fbe0b499

test:
  secret_key_base: 055524487ecc09ff1720ad622342a44b1e3d05200f7b7ec90e78d16caefb6262a0f3a8741e61689449a1fb27891f2606c2f722d4e6c08fac3f25592fe35f2fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
